import { db } from "@db";
import { tasks, clients } from "@shared/schema";
import { eq } from "drizzle-orm";

interface AutoTaskConfig {
  clientId: number;
  clientName: string;
  commentaire?: string;
  statusChange?: {
    newStatus: string;
    oldStatus: string;
  };
}

// Mots-clés pour détecter les appels
const CALL_KEYWORDS = [
  'appeler', 'rappeler', 'rappeller', 'recontacter', 'téléphoner', 'joindre',
  'rappel', 'contact', 'appel', 'téléphone', 'call', 'contacter'
];

// Fonction pour extraire les dates du commentaire
function extractDateFromComment(text: string): Date | null {
  if (!text) return null;
  
  // Patterns de dates possibles
  const datePatterns = [
    /(\d{1,2})\/(\d{1,2})\/(\d{4})/g, // DD/MM/YYYY ou D/M/YYYY
    /(\d{1,2})-(\d{1,2})-(\d{4})/g,  // DD-MM-YYYY ou D-M-YYYY
    /(\d{1,2})\.(\d{1,2})\.(\d{4})/g, // DD.MM.YYYY ou D.M.YYYY
    /(\d{4})-(\d{1,2})-(\d{1,2})/g   // YYYY-MM-DD
  ];
  
  const foundDates: Date[] = [];
  
  // Parcourir tous les patterns pour trouver toutes les dates
  for (const pattern of datePatterns) {
    const matches = Array.from(text.matchAll(pattern));
    
    for (const match of matches) {
      try {
        let day, month, year;
        
        if (pattern === datePatterns[3]) { // YYYY-MM-DD
          [, year, month, day] = match;
        } else { // DD/MM/YYYY formats
          [, day, month, year] = match;
        }
        
        const date = new Date(parseInt(year), parseInt(month) - 1, parseInt(day));
        if (!isNaN(date.getTime())) {
          foundDates.push(date);
        }
      } catch (error) {
        continue;
      }
    }
  }
  
  // Retourner la date la plus récente (future ou présente)
  if (foundDates.length === 0) return null;
  
  // Trier les dates par ordre décroissant (plus récente en premier)
  foundDates.sort((a, b) => b.getTime() - a.getTime());
  
  if (foundDates.length > 1) {
    console.log(`📅 Dates trouvées dans le commentaire: ${foundDates.map(d => d.toLocaleDateString('fr-FR')).join(', ')}`);
    console.log(`📅 Date la plus récente sélectionnée: ${foundDates[0].toLocaleDateString('fr-FR')}`);
  }
  
  return foundDates[0];
}

// Fonction pour détecter si le commentaire nécessite un appel
function isCallRequired(commentaire: string): boolean {
  if (!commentaire) return false;
  
  const lowerComment = commentaire.toLowerCase();
  return CALL_KEYWORDS.some(keyword => lowerComment.includes(keyword));
}

// Fonction pour créer une tâche automatique basée sur le commentaire
export async function createTaskFromComment(config: AutoTaskConfig): Promise<number | null> {
  if (!config.commentaire) return null;
  
  const isCall = isCallRequired(config.commentaire);
  const extractedDate = extractDateFromComment(config.commentaire);
  
  // Définir l'échéance
  let echeance: Date;
  if (extractedDate) {
    echeance = extractedDate;
  } else {
    // Par défaut, échéance dans 2 jours
    echeance = new Date();
    echeance.setDate(echeance.getDate() + 2);
  }
  
  const taskData = {
    userId: 1, // ID par défaut pour les tâches automatiques (admin)
    title: isCall 
      ? `Appeler ${config.clientName}`
      : `Suivi du contrat ${config.clientName}`,
    description: config.commentaire,
    status: 'pending' as const,
    priority: 'medium' as const,
    dueDate: echeance,
    clientId: config.clientId,
    category: isCall ? 'appel' : 'suivi',
    isAutoGenerated: true,
    triggerEvent: 'comment_analysis'
  };
  
  try {
    const [newTask] = await db.insert(tasks).values(taskData).returning();
    console.log(`Tâche automatique créée: ${taskData.title} (ID: ${newTask.id})`);
    return newTask.id;
  } catch (error) {
    console.error('Erreur lors de la création de la tâche automatique:', error);
    return null;
  }
}

// Fonction pour créer une tâche lors d'un changement de statut vers "Post-production"
export async function createTaskFromStatusChange(config: AutoTaskConfig): Promise<number | null> {
  if (!config.statusChange || config.statusChange.newStatus !== 'post_production') {
    return null;
  }
  
  // Échéance : lendemain du changement de statut
  const echeance = new Date();
  echeance.setDate(echeance.getDate() + 1);
  
  const taskData = {
    userId: 1, // ID par défaut pour les tâches automatiques (admin)
    title: `Installation - ${config.clientName}`,
    description: `Reprendre contact avec le client pour comprendre pourquoi l'installation ne s'est pas réalisée`,
    status: 'pending' as const,
    priority: 'high' as const,
    dueDate: echeance,
    clientId: config.clientId,
    category: 'installation',
    isAutoGenerated: true,
    triggerEvent: 'status_change_post_production'
  };
  
  try {
    const [newTask] = await db.insert(tasks).values(taskData).returning();
    console.log(`Tâche automatique post-production créée: ${taskData.title} (ID: ${newTask.id})`);
    return newTask.id;
  } catch (error) {
    console.error('Erreur lors de la création de la tâche post-production:', error);
    return null;
  }
}

// Fonction principale d'automatisation
export async function processTaskAutomation(
  clientId: number,
  options: {
    commentaire?: string;
    statusChange?: { newStatus: string; oldStatus: string };
  }
): Promise<number[]> {
  try {
    // Récupérer les informations du client
    const [client] = await db.select().from(clients).where(eq(clients.id, clientId));
    
    if (!client) {
      console.error(`Client avec ID ${clientId} non trouvé`);
      return [];
    }
    
    const clientName = `${client.prenom} ${client.nom}`;
    const createdTaskIds: number[] = [];
    
    const config: AutoTaskConfig = {
      clientId,
      clientName,
      commentaire: options.commentaire,
      statusChange: options.statusChange
    };
    
    // Traiter la création de tâche basée sur le commentaire
    if (options.commentaire) {
      const taskId = await createTaskFromComment(config);
      if (taskId) {
        createdTaskIds.push(taskId);
      }
    }
    
    // Traiter la création de tâche basée sur le changement de statut
    if (options.statusChange) {
      const taskId = await createTaskFromStatusChange(config);
      if (taskId) {
        createdTaskIds.push(taskId);
      }
    }
    
    console.log(`Automatisation terminée pour ${clientName}. Tâches créées: ${createdTaskIds.length}`);
    return createdTaskIds;
    
  } catch (error) {
    console.error('Erreur dans processTaskAutomation:', error);
    return [];
  }
}